#!/bin/sh

if [ "$(uname)" = "Darwin" ]; then
  echo "RUNNING setup/macOS.sh"
  $HOME/.dotfiles/setup/macOS.sh
elif [ "$(uname)" = "Linux" ]; then
  echo "RUNNING setup/linux.sh"
  $HOME/.dotfiles/setup/linux.sh
fi

