#!/bin/sh

echo "RUNNING setup/main.sh"
$HOME/.dotfiles/setup/main.sh

if [ "$(uname)" = "Darwin" ]; then
  echo "RUNNING setup/macOS/os.sh"
  $HOME/.dotfiles/setup/macOS/os.sh

  echo "RUNNING setup/macOS/other.sh"
  $HOME/.dotfiles/setup/macOS.sh

  read -p "RUN setup/macOS/brewPkgs.sh? (y/n) " response
  if [[ "$response" =~ ^[Yy]$ ]]; then
    echo "RUNNING setup/macOS/brewPkgs.sh"
    $HOME/.dotfiles/setup/macOS/brewPkgs.sh
  fi

elif [ "$(uname)" = "Linux" ]; then
  echo "RUNNING setup/linux.sh"
  $HOME/.dotfiles/setup/linux.sh
fi

