
brew install "age" -q
brew install "aichat" -q
brew install "asciiquarium" -q
brew install "bat" -q
brew install "duti" -q
brew install "git" -q
brew install "gnirehtet" -q
brew install "gnupg" -q
brew install "go" -q
brew install "gradle" -q
brew install "lftp" -q
brew install "libqalculate" -q
brew install "mosquitto" -q
brew install "mpv" -q
brew install "neovim" -q
brew install "node" -q
brew install "rbenv" -q
brew install "sachaos/todoist/todoist" -q
brew install "sox" -q
brew install "sshpass" -q
brew install "tree" -q
brew install "yadm" -q
brew install "zackelia/formulae/bclm" -q
brew install "zsh-autosuggestions" -q
brew install "zsh-syntax-highlighting" -q
brew install "zsh-vi-mode" -q
brew install "1password" -q
brew install "1password-cli" -q
brew install "android-file-transfer" -q
brew install "android-platform-tools" -q
brew install "arc" -q
brew install "blackhole-2ch" -q
brew install "caffeine" -q
brew install "chatgpt" -q
brew install "docker" -q
brew install "flutter" -q
brew install "font-jetbrains-mono-nerd-font" -q
brew install "hiddenbar" -q
brew install "imageoptim" -q
brew install "iterm2" -q
brew install "middleclick" -q
brew install "mission-control-plus" -q
brew install "monitorcontrol" -q
brew install "notunes" -q
brew install "obsidian" -q
brew install "visual-studio-code" -q
