
brew install "age" -q
brew install "aichat" -q
brew install "asciiquarium" -q
brew install "bat" -q
brew install "coreutils" -q
brew install "docker" -q
brew install "duti" -q
brew install "fortune" -q
brew install "fzf" -q
brew install "git" -q
brew install "gnirehtet" -q
brew install "go" -q
brew install "gradle" -q
brew install "graphviz" -q
brew install "helm" -q
brew install "jq" -q
brew install "lftp" -q
brew install "libqalculate" -q
brew install "lorem" -q
brew install "mecab" -q
brew install "mpv" -q
brew install "ncdu" -q
brew install "neovim" -q
brew install "node" -q
brew install "peco" -q
brew install "rbenv" -q
brew install "sachaos/todoist/todoist" -q
brew install "saulpw/vd/visidata" -q
brew install "sl" -q
brew install "speedtest-cli" -q
brew install "sshpass" -q
brew install "textract" -q
brew install "tmux" -q
brew install "tree" -q
brew install "yadm" -q
brew install "zsh-autosuggestions" -q
brew install "zsh-syntax-highlighting" -q
brew install "zsh-vi-mode" -q
brew install "1password" -q
brew install "1password-cli" -q
brew install "android-platform-tools" -q
brew install "android-studio" -q
brew install "arc" -q
brew install "blackhole-2ch" -q
brew install "caffeine" -q
brew install "chatgpt" -q
brew install "flutter" -q
brew install "font-jetbrains-mono-nerd-font" -q
brew install "gcloud-cli" -q
brew install "google-cloud-sdk" -q
brew install "iterm2" -q
brew install "middleclick" -q
brew install "miniconda" -q
brew install "mission-control-plus" -q
brew install "monitorcontrol" -q
brew install "neardrop" -q
brew install "notunes" -q
brew install "obsidian" -q
brew install "rectangle" -q
brew install "visual-studio-code" -q
brew install "whatsapp" -q
