
brew install "age" -q
brew install "aichat" -q
brew install "bat" -q
brew install "duti" -q
brew install "git" -q
brew install "gnupg" -q
brew install "go" -q
brew install "gradle" -q
brew install "mosquitto" -q
brew install "neovim" -q
brew install "node" -q
brew install "rbenv" -q
brew install "sachaos/todoist/todoist" -q
brew install "tree" -q
brew install "yadm" -q
brew install "zackelia/formulae/bclm" -q
brew install "zsh-autosuggestions" -q
brew install "zsh-syntax-highlighting" -q
brew install "zsh-vi-mode" -q
brew install "1password" -q
brew install "android-studio" -q
brew install "arc" -q
brew install "blackhole-2ch" -q
brew install "caffeine" -q
brew install "docker" -q
brew install "dropbox" -q
brew install "flutter" -q
brew install "font-jetbrains-mono-nerd-font" -q
brew install "hiddenbar" -q
brew install "iterm2" -q
brew install "itermai" -q
brew install "kindavim" -q
brew install "middleclick" -q
brew install "mission-control-plus" -q
brew install "monitorcontrol" -q
brew install "notunes" -q
brew install "obsidian" -q
brew install "openmtp" -q
brew install "visual-studio-code" -q
